[project]
name = "goldendoodle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "funcy>=2.0",
    "gunicorn>=23.0.0",
]
